# Generated by Django 4.2.1 on 2023-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_topic', models.CharField(max_length=20)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_begtime', models.TimeField()),
                ('meeting_endtime', models.TimeField()),
                ('meeting_participants', models.TextField(max_length=100)),
            ],
        ),
    ]
