# Generated by Django 4.2.1 on 2023-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='meeting_begtime',
            new_name='meeting_begin_time',
        ),
        migrations.RenameField(
            model_name='meetings',
            old_name='meeting_endtime',
            new_name='meeting_ending_time',
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meeting_date',
            field=models.DateField(),
        ),
    ]
